# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Arthur.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1356, 803)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.templateLineEdit = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templateLineEdit.sizePolicy().hasHeightForWidth())
        self.templateLineEdit.setSizePolicy(sizePolicy)
        self.templateLineEdit.setObjectName("templateLineEdit")
        self.gridLayout_2.addWidget(self.templateLineEdit, 4, 0, 1, 1)
        self.subjectBodyLineEdit = QtWidgets.QLineEdit(self.frame)
        self.subjectBodyLineEdit.setObjectName("subjectBodyLineEdit")
        self.gridLayout_2.addWidget(self.subjectBodyLineEdit, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.attachmentBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attachmentBtn.sizePolicy().hasHeightForWidth())
        self.attachmentBtn.setSizePolicy(sizePolicy)
        self.attachmentBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.attachmentBtn.setMaximumSize(QtCore.QSize(150, 400))
        self.attachmentBtn.setObjectName("attachmentBtn")
        self.horizontalLayout_3.addWidget(self.attachmentBtn)
        self.attachmentLabel = QtWidgets.QLabel(self.frame)
        self.attachmentLabel.setObjectName("attachmentLabel")
        self.horizontalLayout_3.addWidget(self.attachmentLabel)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.receipientLabel = QtWidgets.QLabel(self.frame_2)
        self.receipientLabel.setObjectName("receipientLabel")
        self.verticalLayout_2.addWidget(self.receipientLabel)
        self.receipientTextEdit = QtWidgets.QTextEdit(self.frame_2)
        self.receipientTextEdit.setObjectName("receipientTextEdit")
        self.verticalLayout_2.addWidget(self.receipientTextEdit)
        self.progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.sendMailBtn = QtWidgets.QPushButton(self.frame_2)
        self.sendMailBtn.setObjectName("sendMailBtn")
        self.verticalLayout_2.addWidget(self.sendMailBtn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sentLabel = QtWidgets.QLabel(self.frame_2)
        self.sentLabel.setObjectName("sentLabel")
        self.verticalLayout.addWidget(self.sentLabel)
        self.sentListWidget = QtWidgets.QListWidget(self.frame_2)
        self.sentListWidget.setObjectName("sentListWidget")
        self.verticalLayout.addWidget(self.sentListWidget)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.failedSentList = QtWidgets.QListWidget(self.frame_2)
        self.failedSentList.setObjectName("failedSentList")
        self.verticalLayout.addWidget(self.failedSentList)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1356, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Email Subject"))
        self.label.setText(_translate("MainWindow", "Email Body"))
        self.attachmentBtn.setText(_translate("MainWindow", "Add Attachment"))
        self.attachmentLabel.setText(_translate("MainWindow", "No Attachment Chosen"))
        self.receipientLabel.setText(_translate("MainWindow", "Receipients"))
        self.sendMailBtn.setText(_translate("MainWindow", "Send Emails"))
        self.sentLabel.setText(_translate("MainWindow", "Sent"))
        self.label_3.setText(_translate("MainWindow", "Failed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
